# Generated by Django 5.2.13 on 2026-04-11 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=32)),
                ('event_type', models.CharField(max_length=120)),
                ('event_id', models.CharField(max_length=160, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=32)),
                ('provider_account_id', models.CharField(max_length=128)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('profile_image_url', models.URLField(blank=True)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('not_connected', 'Not Connected'), ('syncing', 'Syncing'), ('expired', 'Expired'), ('reconnect_required', 'Reconnect Required'), ('failed', 'Failed')], default='not_connected', max_length=32)),
                ('token_status', models.CharField(choices=[('active', 'Active'), ('expiring', 'Expiring'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=32)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'provider'),
                'unique_together': {('user', 'provider', 'provider_account_id')},
            },
        ),
        migrations.CreateModel(
            name='PlatformProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=160)),
                ('bio', models.TextField(blank=True)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('reach_count', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('source_type', models.CharField(choices=[('connected_platform', 'Connected Platform'), ('manual', 'Manual'), ('imported', 'Imported')], default='connected_platform', max_length=32)),
                ('verification_state', models.CharField(choices=[('verified', 'Verified'), ('self_reported', 'Self Reported'), ('expired', 'Expired'), ('unavailable', 'Unavailable')], default='verified', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('connected_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_profile', to='connected_accounts.connectedaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField()),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('total_reach', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('account_engaged', models.PositiveIntegerField(default=0)),
                ('hook_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('verification_state', models.CharField(choices=[('verified', 'Verified'), ('self_reported', 'Self Reported'), ('expired', 'Expired'), ('unavailable', 'Unavailable')], default='verified', max_length=32)),
                ('source_type', models.CharField(choices=[('connected_platform', 'Connected Platform'), ('manual', 'Manual'), ('imported', 'Imported')], default='connected_platform', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('platform_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='connected_accounts.platformprofile')),
            ],
            options={
                'ordering': ('-captured_at',),
            },
        ),
        migrations.CreateModel(
            name='PlatformMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('media_type', models.CharField(max_length=64)),
                ('section', models.CharField(blank=True, max_length=64)),
                ('thumbnail_theme', models.CharField(blank=True, max_length=80)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('verification_state', models.CharField(choices=[('verified', 'Verified'), ('self_reported', 'Self Reported'), ('expired', 'Expired'), ('unavailable', 'Unavailable')], default='verified', max_length=32)),
                ('source_type', models.CharField(choices=[('connected_platform', 'Connected Platform'), ('manual', 'Manual'), ('imported', 'Imported')], default='connected_platform', max_length=32)),
                ('platform_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='connected_accounts.platformprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(max_length=80)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('connected_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='connected_accounts.connectedaccount')),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
    ]
