# Generated by Django 5.2.13 on 2026-04-11 11:44

import apps.accounts.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active_role', models.CharField(choices=[('creator', 'Creator'), ('brand', 'Brand')], default='creator', max_length=20)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', apps.accounts.models.SetzaUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('primary_role', models.CharField(choices=[('creator', 'Creator'), ('brand', 'Brand')], default='creator', max_length=20)),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('banner_theme', models.CharField(default='theme-hero-night', max_length=80)),
                ('avatar_theme', models.CharField(default='theme-avatar-rose', max_length=80)),
                ('pricing_range', models.CharField(blank=True, max_length=80)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('audience_types', models.JSONField(blank=True, default=list)),
                ('traits', models.JSONField(blank=True, default=list)),
                ('status_tags', models.JSONField(blank=True, default=list)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('age_range', models.CharField(blank=True, max_length=32)),
                ('niches', models.JSONField(blank=True, default=list)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('reach_count', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('hook_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('account_engaged', models.PositiveIntegerField(default=0)),
                ('match_keywords', models.JSONField(blank=True, default=list)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('focus_tags', models.JSONField(blank=True, default=list)),
                ('avg_campaign_engagement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('campaign_frequency', models.CharField(blank=True, max_length=32)),
                ('repeated_creators_rate', models.CharField(blank=True, max_length=32)),
                ('avg_event_footfall', models.CharField(blank=True, max_length=32)),
                ('creator_partners_count', models.PositiveIntegerField(default=0)),
                ('match_keywords', models.JSONField(blank=True, default=list)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to='accounts.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('creator', 'Creator'), ('brand', 'Brand')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'role'),
                'unique_together': {('user', 'role')},
            },
        ),
    ]
