# Generated by Django 5.2.13 on 2026-04-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('overview', models.TextField(blank=True)),
                ('budget_min', models.PositiveIntegerField(default=0)),
                ('budget_max', models.PositiveIntegerField(default=0)),
                ('follower_min', models.PositiveIntegerField(default=0)),
                ('follower_max', models.PositiveIntegerField(default=0)),
                ('engagement_requirement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('media_theme', models.CharField(default='theme-media-nightlife-1', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('brand_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='accounts.brandprofile')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
