# Generated by Django 5.2.13 on 2026-04-11 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('collaborations', '0001_initial'),
        ('opportunities', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic_type', models.CharField(choices=[('service', 'Service'), ('opportunity', 'Opportunity'), ('collaboration', 'Collaboration')], default='service', max_length=20)),
                ('topic_label', models.CharField(blank=True, max_length=180)),
                ('last_message_preview', models.CharField(blank=True, max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count_creator', models.PositiveIntegerField(default=0)),
                ('unread_count_brand', models.PositiveIntegerField(default=0)),
                ('brand_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_conversations', to='accounts.brandprofile')),
                ('collaboration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='collaborations.collaboration')),
                ('creator_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_conversations', to='accounts.creatorprofile')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='opportunities.opportunity')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='services.service')),
            ],
            options={
                'ordering': ('-last_message_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
