# Generated by Django 5.2.13 on 2026-04-11 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('price_from', models.PositiveIntegerField(default=0)),
                ('turnaround_days', models.PositiveIntegerField(default=0)),
                ('concepts', models.PositiveIntegerField(default=0)),
                ('revisions', models.PositiveIntegerField(default=0)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('media_theme', models.CharField(default='theme-media-lifestyle-1', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('creator_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.creatorprofile')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
